language: generic
sudo: required
services:
  - docker


before_install:
  - docker build -t syedwahed/docker-react -f Dockerfile.dev .

script:
  - docker run syedwahed/docker-react npm run test -- --coverage
